config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
  resources :pages
  root 'home#index'
  resources :contacts, only: [:new, :create, :show]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming
  attr_accessor :name, :email, :message

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :by_newest, Post::Scopes::ByNewest.new
end

app/models/post/scopes/by_newest.rb
class Post::Scopes::ByNewest
  def call
    Post.order('created_at desc')
  end
end

app/models/site_config.rb
class SiteConfig
  def self.logo
    ENV['SITE_NAME']
  end
  def self.title
    ENV['SITE_TITLE']
  end
  def self.heading_title
    ENV['SITE_HEADING_TITLE']
  end
  def self.heading_subtitle
    ENV['SITE_HEADING_SUBTITLE']
  end
  def self.facebook_url
    ENV['FACEBOOK_URL']
  end
  def self.twitter_url
    ENV['TWITTER_URL']
  end
  def self.github_url
    ENV['GIHUB_URL']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def present(model, presenter_class=nil)
    klass = presenter_class || "#{model.class.name}Presenter".constantize
    presenter = klass.new(model, self)
    presenter
  end
  helper_method :present, :present_pages
  def present_pages
    present(Page, PagePresenter).all_pages
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def new
    instance_variable_set("@#{target.downcase}", target_class.new)
  end

  def show
    instance_variable_set("@#{target.downcase}", find_target_class)
  end

  def create
    if initialized_class.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    instance_variable_set("@#{target.downcase}", find_target_class)
  end

  def update
    if find_target_class.update_attributes(target_params)
      redirect_to find_target_class
    else
      render :edit
    end
  end

  def destroy
    find_target_class.destroy
    redirect_to root_path
  end

  private
  # Assuming target controller is PostsController
  # Returns 'Post' as string
  def target
    controller_path.classify
  end

  # Returns Post class
  def target_class
    target.constantize
  end

  # Same as Post.find(params[:id])
  def find_target_class
    target_class.find(params[:id])
  end

  # Same as Post.new(post_params)
  def initialized_class
    target_class.new(target_params)
  end

  #Returns :post
  def target_to_sym
    target.downcase.to_sym
  end

  def target_params
    params.require(target_to_sym).permit(target_class.column_names)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < BaseController
  def create
    contact = Contact.new(params[:contact])
    ContactMailer.admin_notification(contact).deliver
    redirect_to root_path, flash: { success: success_message }
  end
  private
  def success_message
    "Thanks for reaching out, I'll be in touch shortly!
     meanwhile, feel free to go through my blog."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.by_newest
  end
end

app/controllers/pages_controller.rb
class PagesController < BaseController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/posts_controller.rb
class PostsController < BaseController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_heading_title
    SiteConfig.heading_title
  end
  def default_heading_subtitle
    SiteConfig.heading_subtitle
  end
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-error',
      alert: 'alert-block', notice: 'alert-info' }[flash_type] || flash_type.to_s
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  extend ApplicationHelper

  def markdown(text)
    render_options = {
      # will remove from the output HTML tags inputted by user
      filter_html:     true,
      # will insert <br /> tags in paragraphs where are newlines
      # (ignored by default)
      hard_wrap:       true,
      # hash for extra link options, for example 'nofollow'
      link_attributes: { rel: 'nofollow' }
      # more
      # will remove <img> tags from output
      # no_images: true
      # will remove <a> tags from output
      # no_links: true
      # will remove <style> tags from output
      # no_styles: true
      # generate links for only safe protocols
      # safe_links_only: true
      # and more ... (prettify, with_toc_data, xhtml)
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      #will parse links without need of enclosing them
      autolink:           true,
      # blocks delimited with 3 ` or ~ will be considered as code block.
      # No need to indent.  You can provide language name too.
      # ```ruby
      # block of code
      # ```
      fenced_code_blocks: true,
      # will ignore standard require for empty lines surrounding HTML blocks
      lax_spacing:        true,
      # will not generate emphasis inside of words, for example no_emph_no
      no_intra_emphasis:  true,
      # will parse strikethrough from ~~, for example: ~~bad~~
      strikethrough:      true,
      # will parse superscript after ^, you can wrap superscript in ()
      superscript:        true,
      tables: true,
      # will require a space after # in defining headers
      # space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/views/contacts/_form.html.haml
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      .row.control-group
        .form-group.col-xs-12.floating-label-form-group.c
          = form_for @contact do |f|
            = f.text_field :name, placeholder: 'Your Name', size: 69
            %hr
            = f.text_field :email, placeholder: 'Your Email', size: 69
            %hr
            = f.text_area :message, placeholder: 'Your Message', size: 69
            %hr
            = f.submit 'Send', class: 'btn btn-default'

app/views/contacts/new.html.haml
= content_for :title, 'Contact Me'
= content_for :subtitle, 'leave me a quick message!'
= render 'form'

app/views/home/index.html.haml
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      -@posts.each do |post|
        .post-preview
          = link_to post do
            %h2.post-title
              = post.title
            %h3.post-subtitle
              = post.subtitle
          %p.post-meta
            Posted
            on #{present(post).created_at_formatted}
%hr/

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= SiteConfig.title
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Custom Fonts
    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
  %body
    / Navigation
    %nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header.page-scroll
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to SiteConfig.logo, root_path, class: "navbar-brand"
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Contact me', new_contact_path
            - present_pages.each do |page|
              %li
                = link_to page.title, page
            - if current_admin
              %li
                = link_to 'New Page', new_page_path
              %li
                = link_to 'New Post', new_post_path
              %li
                = link_to 'Log Out', destroy_admin_session_path
        / /.navbar-collapse
      / /.container
    %header.intro-header{:style => "background-image: url(#{asset_path 'home-bg.jpg'})"}
      .container
        .row
          .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
            .site-heading
              = render partial: "shared/flash_messages", flash: flash
              %h1= content_for?(:title) ? yield(:title) : default_heading_title
              %hr.small/
              %span.subheading= content_for?(:subtitle) ? yield(:subtitle) : default_heading_subtitle
    = yield
    / Footer
    %footer
      .container
        .row
          .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
            %ul.list-inline.text-center
              %li
                %a{:href => SiteConfig.twitter_url}
                  %span.fa-stack.fa-lg
                    %i.fa.fa-circle.fa-stack-2x
                    %i.fa.fa-twitter.fa-stack-1x.fa-inverse
              %li
                %a{:href => SiteConfig.facebook_url}
                  %span.fa-stack.fa-lg
                    %i.fa.fa-circle.fa-stack-2x
                    %i.fa.fa-facebook.fa-stack-1x.fa-inverse
              %li
                %a{:href => SiteConfig.github_url}
                  %span.fa-stack.fa-lg
                    %i.fa.fa-circle.fa-stack-2x
                    %i.fa.fa-github.fa-stack-1x.fa-inverse
            %p.copyright.text-muted
              Copyright © #{SiteConfig.title} #{Time.now.year}
              %br Love my blog?
              = link_to 'Fork it!', 'https://github.com/anonyo/simple-blog'

app/views/pages/_control_panel.html.haml
%p= link_to 'Edit Page', edit_page_path, class: 'btn btn-default'
%p= link_to 'Delete Page', page, method: :delete, class: 'btn btn-default'

app/views/pages/_form.html.haml
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      .row.control-group
        .form-group.col-xs-12.floating-label-form-group.controls
          = form_for @page do |f|
            = f.text_field :title, placeholder: 'Page Title', size: 69
            %hr
            = f.text_field :subtitle, placeholder: 'Page Subtitle', size: 69
            %hr
            = f.text_area :body,  placeholder: 'Page Body, markdown supported!', size: '69x30'
            %hr
            = f.submit 'Submit', class: 'btn btn-default'

app/views/pages/edit.html.haml
= content_for :title, 'Editing'
= content_for :subtitle, @page.title
= render 'form'

app/views/pages/new.html.haml
= content_for :title, 'New Page'
= content_for :subtitle, 'Create new Page'
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      .row.control-group
        .form-group.col-xs-12.floating-label-form-group.controls
          = render 'form'

app/views/pages/show.html.haml
= content_for :title, @page.title
= content_for :subtitle, @page.subtitle
%article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        %p= markdown @page.body
        - if current_admin
          = render 'control_panel', page: @page
%hr/

app/views/posts/_control_panel.html.haml
%p= link_to 'Edit Post', edit_post_path, class: 'btn btn-default'
%p= link_to 'Delete Post', post, method: :delete, class: 'btn btn-default'

app/views/posts/_form.html.haml
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      .row.control-group
        .form-group.col-xs-12.floating-label-form-group.controls
          = form_for @post do |f|
            = f.text_field :title, placeholder: 'Title', size: 69
            %hr
            = f.text_field :subtitle, placeholder: 'Subtitle', size: 69
            %hr
            = f.text_area :body, placeholder: 'Body, markdown supported!', size: '69x30'
            %hr
            = f.submit 'Submit', class: 'btn btn-default'

app/views/posts/edit.html.haml
= content_for :title, 'Editing'
= content_for :subtitle, @post.title
= render 'form'

app/views/posts/new.html.haml
= content_for :title, 'New Post'
= content_for :subtitle, 'Create new blog post'
= render 'form'

app/views/posts/show.html.haml
= content_for :title, @post.title
= content_for :subtitle, @post.subtitle
%article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        %p= markdown @post.body
        - if current_admin
          = render 'control_panel', post: @post
%hr/

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message